README.md
Atualização do readme com links de apoio.
=> Atualizaçao do README.md

src/models/PessoaFisica.js
The model of Pessoa Fisica and CRUD functions.
Fixes #4
=> finished the pessoa fisica model

src/models/PessoaJuridica.js
Finished the pessoa juridica model.
Fixes #5
=> finished the pessoa juridica model

src/models/ProdutoPedido.js
Finished the product_order model
Fixes #12
=> finished the produto_pedido model

.eslintrc.json, src/controllers/PessoaJuridicaController.js, src/routes.js
=> adicionado funçoes de controller

src/controllers/PedidoController.js, src/models/Pedido.js, src/models/ProdutoPedido.js, src/routes.js
=> controller de pedido e rotas

src/controllers/CarrinhoController.js, src/models/Endereco.js, src/models/ProdutoPedido.js, src/routes.js
Finalizado o controller de carrinho.
=> finalizado o controller de carrinho

src/routes.js, src/views/cart.ejs, src/views/css/pegue.css, src/views/payment.ejs, src/views/pegue.ejs
=> page pegue

src/views/css/header.css, src/views/js/openMenu.js, src/views/partials/header.ejs
create the submenu user
submenu user when his logged in
=> submenu user

src/routes.js, src/views/cart.ejs, src/views/css/login.css, src/views/js/verify.js, src/views/login.ejs, src/views/partials/header.ejs
=> login page

src/routes.js, src/views/css/search.css, src/views/js/openMenu.js, src/views/search.ejs
page search and filters, dropdown menus etc
=> page search and filters

src/css/addAddress.css, src/routes.js, src/views/addAddress.ejs, src/views/address.ejs, src/views/css/address.css, src/views/css/myOrders.css, src/views/css/titlePage.css, src/views/myOrders.ejs
page my address and page my list orders
=> page my address and page my list orders

src/routes.js, src/views/css/addAddress.css, src/views/css/index.css, src/views/editAddress.ejs, src/views/js/cep.js
feature address (edit, add, see)
=> add page about address, edit js cep, edit index e routes

src/controllers/EnderecoController.js, src/controllers/UsuarioController.js, src/models/Endereco.js, src/models/Usuario.js, src/routes.js
- Funções das rotas
- Funções do CRUD
=> finalizado o controller de endereco

src/controllers/EnderecoController.js, src/routes.js
Adicionado uma rota para mostrar informações de um único endereço
=> adicionado nova rota de endereço

src/controllers/ProdutoController.js, src/models/Produto.js, src/routes.js
=> adicionado novas rotas de produto

src/routes.js, src/views/css/myprofile.css, src/views/css/profile.css, src/views/css/sold.css, src/views/myprofile.ejs, src/views/profile.ejs, src/views/sold.ejs
=> profile page

src/controllers/SearchController.js, src/models/Produto.js, src/models/Usuario.js, src/routes.js
finalizado o controller de busca
=> finalizado o controller de busca

src/controllers/AnuncioController.js, src/controllers/ProdutoController.js, src/models/Anuncio.js, src/models/Produto.js, src/routes.js
Finalizado o model e controller de anuncio
=> finalizado model e controller de anuncio

src/controllers/AnuncioController.js, src/controllers/CarrinhoController.js, src/controllers/EnderecoController.js, src/controllers/ProdutoController.js, src/controllers/SessionController.js, src/controllers/UsuarioController.js, src/models/Usuario.js, src/routes.js
finalizado controller de sessao
=> finalizado controller de sessao

.sequelizerc, src/controllers/EnderecoController.js, src/controllers/PedidoController.js, src/controllers/ProdutoController.js, src/controllers/UsuarioController.js, src/database/index.js, src/database/migrations/20191130233053-create-users.js, src/database/migrations/20191201000112-create-addressess.js, src/database/migrations/20191201000551-create-categories.js, src/database/migrations/20191201002331-create-products.js, src/database/migrations/20191201002820-create-orders.js, src/database/migrations/20191201003327-create-announcements.js, src/database/migrations/20191201004057-create-questions.js, src/database/migrations/20191201004222-create-answers.js, src/database/migrations/20191201021545-create-order_products.js, src/database/migrations/20191201025050-create-product_categories.js, src/database/seeders/20191201195513-categories.js, src/models/Anuncio.js, src/models/Categoria.js, src/models/Endereco.js, src/models/Pedido.js, src/models/Pergunta.js, src/models/Produto.js, src/models/Resposta.js, src/models/Usuario.js, src/routes.js
adicionado rotas de produto e pedido
=> adicionado rotas de produto e pedido

src/controllers/CarrinhoController.js, src/models/Pedido.js, src/models/Produto.js, src/routes.js
=> finalizado rota do carrinho

src/controllers/AnuncioController.js, src/controllers/CarrinhoController.js, src/models/Anuncio.js, src/routes.js
=> finalizado rota de anuncios

src/controllers/SessionController.js, src/routes.js
=> finalizado rota de sessao

src/controllers/SearchController.js, src/routes.js
=> finalizado rotas de busca

src/views/createad.ejs, src/views/js/address.js, src/views/js/anuncios.js, src/views/js/createAd.js, src/views/js/editAddress.js, src/views/js/setCategoria.js, src/views/myprofile.ejs
=> criar, edit, remove endereco
